name: financia_edu
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.7.2

dependencies:
   flutter:
      sdk: flutter
   fl_chart: ^0.64.0
   hive: ^2.2.3
   hive_flutter: ^1.1.0
   path_provider: ^2.1.2
   intl: ^0.18.0
   image_picker: ^1.0.4
   url_launcher: ^6.2.6
   firebase_core: ^3.13.0
   firebase_auth: ^5.5.3
   shared_preferences: ^2.2.2
   device_info_plus: ^11.4.0
   cloud_firestore: ^5.6.7

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^5.0.0

flutter:
   uses-material-design: true
